#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S4,     IRSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          RightBallSpin, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          FrontBallSpin, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          LeftBallSpin,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     FRONT_LEFT_WHEEL, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     LeftLift,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     RightLift,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     FRONT_RIGHT_WHEEL, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     BACK_LEFT_WHEEL, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     BACK_RIGHT_WHEEL, tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    LeftTilt,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    RightTilt,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    RightHook,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    LeftHook,             tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//1 = forward
//2 = left
//3 = backwards
//4 = right
int Speed = 50;

void move(int dir, float seconds)
{
	if(dir == 1)
	{
		motor[FRONT_RIGHT_WHEEL] = Speed;
		motor[BACK_RIGHT_WHEEL] = Speed;
		motor[FRONT_LEFT_WHEEL] = Speed;
		motor[BACK_LEFT_WHEEL] = Speed;

		wait10Msec(seconds * 100);

		motor[FRONT_RIGHT_WHEEL] = 0;
		motor[BACK_RIGHT_WHEEL] = 0;
		motor[FRONT_LEFT_WHEEL] = 0;
		motor[BACK_LEFT_WHEEL] = 0;
	}
	if(dir == 2)
	{
		motor[FRONT_RIGHT_WHEEL] = Speed;
		motor[BACK_RIGHT_WHEEL] = Speed;
		motor[FRONT_LEFT_WHEEL] = Speed;
		motor[BACK_LEFT_WHEEL] = Speed;
		wait10Msec(seconds * 100);

		motor[FRONT_RIGHT_WHEEL] = 0;
		motor[BACK_RIGHT_WHEEL] = 0;
		motor[FRONT_LEFT_WHEEL] = 0;
		motor[BACK_LEFT_WHEEL] = 0;
	}

	if(dir == 3)
	{
		motor[FRONT_RIGHT_WHEEL] = Speed;
		motor[BACK_RIGHT_WHEEL] = Speed;
		motor[FRONT_LEFT_WHEEL] = Speed;
		motor[BACK_LEFT_WHEEL] = Speed;

		wait10Msec(seconds * 100);

		motor[FRONT_RIGHT_WHEEL] = 0;
		motor[BACK_RIGHT_WHEEL] = 0;
		motor[FRONT_LEFT_WHEEL] = 0;
		motor[BACK_LEFT_WHEEL] = 0;
	}

	if(dir == 4)
	{
		motor[FRONT_RIGHT_WHEEL] = Speed;
		motor[BACK_RIGHT_WHEEL] = Speed;
		motor[FRONT_LEFT_WHEEL] = Speed;
		motor[BACK_LEFT_WHEEL] = Speed;
		wait10Msec(seconds * 100);

		motor[FRONT_RIGHT_WHEEL] = 0;
		motor[BACK_RIGHT_WHEEL] = 0;
		motor[FRONT_LEFT_WHEEL] = 0;
		motor[BACK_LEFT_WHEEL] = 0;
	}

}
//1 = forward
//2 = left
//3 = backward
//4 = right

task main()
{
	//3 Is facing parking zone
	if(SensorValue[IRSeeker] == )
	{
	move(1, 1.0);
	move(2, 1.0);
	move(1, 0.5);
	move(2, 0.5);
	}

	//2 Is facing parking zone
	if(SensorValue[IRSeeker] == )
	{

	}
	//1 Is facing parking zone
	if(SensorValue[IRSeeker] == )
	{

	}

}
