#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     BACK_RIGHT_WHEEL, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     FRONT_RIGHT_WHEEL, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     FRONT_LEFT_WHEEL, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     BACK_LEFT_WHEEL, tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"
task main()
{
	getJoystickSettings(joystick);
	int THRESHOLD = 60;
	int SPEED = 50;
while(true)
{
	//Forward Movement
	if((joystick.joy1_y1) < -THRESHOLD && abs(joystick.joy1_x1) < THRESHOLD)
	{
		motor[FRONT_RIGHT_WHEEL] = SPEED;
		motor[BACK_RIGHT_WHEEL] = SPEED;
		motor[FRONT_LEFT_WHEEL] = -SPEED;
		motor[BACK_LEFT_WHEEL] = -SPEED;
  }
		else
	{
		motor[FRONT_RIGHT_WHEEL] = 0;
		motor[BACK_RIGHT_WHEEL] = 0;
		motor[FRONT_LEFT_WHEEL] = 0;
		motor[BACK_LEFT_WHEEL] = 0;
	}

	//Backward Movement
	if((joystick.joy1_y1) < THRESHOLD && abs(joystick.joy1_x1) < THRESHOLD)
	{
		motor[FRONT_RIGHT_WHEEL] = -SPEED;
		motor[BACK_RIGHT_WHEEL] = -SPEED;
		motor[FRONT_LEFT_WHEEL] = SPEED;
		motor[BACK_LEFT_WHEEL] = SPEED;
	}
		else
	{
		motor[FRONT_RIGHT_WHEEL] = SPEED;
		motor[BACK_RIGHT_WHEEL] = SPEED;
		motor[FRONT_LEFT_WHEEL] = SPEED;
		motor[BACK_LEFT_WHEEL] = SPEED;
	}

	//Right Movement
	if((joystick.joy1_x1) < THRESHOLD && abs(joystick.joy1_y1) < THRESHOLD)
	{
		motor[FRONT_RIGHT_WHEEL] = -SPEED;
		motor[BACK_RIGHT_WHEEL] = SPEED;
		motor[FRONT_LEFT_WHEEL] = -SPEED;
		motor[BACK_LEFT_WHEEL] = SPEED;
	}
		else
	{
		motor[FRONT_RIGHT_WHEEL] = SPEED;
		motor[BACK_RIGHT_WHEEL] = SPEED;
		motor[FRONT_LEFT_WHEEL] = SPEED;
		motor[BACK_LEFT_WHEEL] = SPEED;
	}

	//Left Movement
	if((joystick.joy1_x1) < -THRESHOLD && abs(joystick.joy1_y1) < THRESHOLD)
	{
		motor[FRONT_RIGHT_WHEEL] = SPEED;
		motor[BACK_RIGHT_WHEEL] = -SPEED;
		motor[FRONT_LEFT_WHEEL] = SPEED;
		motor[BACK_LEFT_WHEEL] = -SPEED;
	}
		else
	{
		motor[FRONT_RIGHT_WHEEL] = SPEED;
		motor[BACK_RIGHT_WHEEL] = SPEED;
		motor[FRONT_LEFT_WHEEL] = SPEED;
		motor[BACK_LEFT_WHEEL] = SPEED;
	}
}
}
