#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S4,     IRSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          RightBallSpin, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          FrontBallSpin, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          LeftBallSpin,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     FRONT_LEFT_WHEEL, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     LeftLift,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     RightLift,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     FRONT_RIGHT_WHEEL, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     BACK_LEFT_WHEEL, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     BACK_RIGHT_WHEEL, tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    LeftTilt,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    RightTilt,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    RightHook,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    LeftHook,             tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
task main()
{
	getJoystickSettings(joystick); //Gets the controller settings so robotc can read the values

	waitForStart();//Wait for the TeleOP period to begin

	//Delcaring Variables
	int Threshold = 60; //Threshold for joystick values
	int Forward = 0;
	int Backward = 0;
	int Right = 0;
	int Left = 0;
	int Spin = 0;
	int RightBumper = 6;
	int LeftTrigger = 7;
	int RightTrigger = 8;
	int TopHat1 = joystick.joy1_TopHat;
	int TopHat2 = joystick.joy2_TopHat;
	int X = 1; //X button on the controller
	int A = 2; //A button on the

	//Dual controller control
	int JoystickOutput1Y = joystick.joy1_y1 + joystick.joy2_y1;
	int JoystickOutput1X = joystick.joy1_x1 + joystick.joy2_x1;
	int JoystickOutput2Y = joystick.joy1_y2 + joystick.joy2_y2;
	int JoystickOutput2X = joystick.joy1_x2 + joystick.joy2_x2;
	int MaxEncoderRotations = 60; //Max roations the motors can make extend the lift to maximum height

	//Reseting encorder values
	nMotorEncoder[LeftLift] = 0;
	nMotorEncoder[RightLift] = 0;

	//Loops and checks outputs from the controllers
	while(true)
	{
		//Redefining variables to enable dual controller control
		JoystickOutput1Y = joystick.joy1_y1 + joystick.joy2_y1;
		JoystickOutput1X = joystick.joy1_x1 + joystick.joy2_x1;
		JoystickOutput2Y = joystick.joy1_y2 + joystick.joy2_y2;
		JoystickOutput2X = joystick.joy1_x2 + joystick.joy2_x2;

		//Stop motors connect to the wheels if controller has no output, if there is an output the rest of the statements are checked
		if(abs(JoystickOutput1X) < Threshold && abs(JoystickOutput1Y) < Threshold && abs(JoystickOutput2X) < Threshold && abs(JoystickOutput2Y) < Threshold)
		{
			motor[FRONT_RIGHT_WHEEL] = 0;
			motor[BACK_RIGHT_WHEEL] = 0;
			motor[FRONT_LEFT_WHEEL] = 0;
			motor[BACK_LEFT_WHEEL] = 0;
			Forward = 0;
			Backward = 0;
			Right = 0;
			Left = 0;
			Spin = 0;
			Sleep(1);
		}
			else
		{
			//Forward Movement
			if((JoystickOutput1Y) < -Threshold)
			{
				Forward = JoystickOutput1Y;
			}

			//Backward Movement
			if((JoystickOutput1Y) > Threshold)
			{
				Backward = JoystickOutput1Y;
			}

			//Right Movement
			if((JoystickOutput1X) > Threshold)
			{
				Right = JoystickOutput1X;
			}

			//Left Movement
			if((JoystickOutput1X) < -Threshold)
			{
				Left = JoystickOutput1X;
			}

			//Spin Left
			if((JoystickOutput2X) < -Threshold)
			{
				Spin = JoystickOutput2X;
			}

			//Spin Right
			if((JoystickOutput2X) > Threshold)
			{
				Spin = JoystickOutput2X;
			}
		}

		//Stops all motors and servos if there is no controller output, if there is an output the rest of the statements are checked
		if(joy1Btn(RightBumper) == 0 && joy2Btn(RightBumper) == 0 && joy1Btn(RightTrigger) == 0 && joy2Btn(RightTrigger) == 0 && joy1Btn(X) == 0 && joy2Btn(X) == 0 && joy1Btn(A) == 0 && joy2Btn(A) == 0)
		{
			//Ball Collectors
			if(joy1Btn(RightBumper) == 1 || joy2Btn(RightBumper) == 1)
			{
				motor[LeftBallSpin] = 100;
				motor[FrontBallSpin] = 100;
				motor[RightBallSpin] = 100;
			}

			//Lift Up
			if(joy1Btn(RightTrigger) == 1 || joy2Btn(RightTrigger) == 1 && nMotorEncoder[LeftLift] < MaxEncoderRotations && nMotorEncoder[RightLift] < MaxEncoderRotations)
			{
				motor[LeftLift] = 100;
				motor[RightLift] = 100;
			}

			//Lift Down
			if(joy1Btn(LeftTrigger) == 1 || joy2Btn(LeftTrigger) == 1)
			{
				motor[LeftLift] = -100;
				motor[RightLift] = -100;
			}

			//Hook Down
			if(joy1Btn(X) == 1 || joy2Btn(X) == 1)
			{
				servo[LeftHook] = 180;
				servo[RightHook] = 180;
			}

			//Hook Up
			if(joy1Btn(A) == 1 || joy2Btn(A) == 1)
			{
				servo[LeftHook] = 0;
				servo[RightHook] = 0;
			}

			//Tilt Down
			if(joystick.joy1_TopHat == 4 || joystick.joy2_TopHat == 4)
			{
				servo[LeftTilt] = 180;
				servo[RightTilt] = 180;
			}

			//Tilt Up
			if(joystick.joy1_TopHat == 0 || joystick.joy2_TopHat == 0)
			{
				servo[LeftTilt] = 0;
				servo[RightTilt] = 0;
			}
		}

		//Setting movement motor values
		motor[FRONT_RIGHT_WHEEL] = -Forward + -Backward + Left + Right + Spin;
		motor[BACK_RIGHT_WHEEL] = -Forward + -Backward + -Left + -Right + Spin;
		motor[FRONT_LEFT_WHEEL] = Forward + Backward + Left + Right + Spin;
		motor[BACK_LEFT_WHEEL] = Forward + Backward + -Left + -Right + Spin;

		}
}
